services:
  portfolio:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER:-kavarera}/portofolio-svelte:latest
    container_name: portofolio_svelte
    restart: unless-stopped
    ports:
      - "3000:80"
    deploy:
      resources:
        limits:
          memory: 30M

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase_porto
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data
    deploy:
      resources:
        limits:
          memory: 40M
